apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: utility-prod

namePrefix: prod-

images:
  - name: utility-api
    newName: utility-api
    newTag: stable
