apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: utility-dev

namePrefix: dev-

images:
  - name: utility-api
    newName: wmcdonald/utility-api
    newTag: latest
